set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(_PICO_ARM "$ENV{USERPROFILE}/.pico-sdk/toolchain/15_2_Rel1/bin")
if(EXISTS "${_PICO_ARM}/arm-none-eabi-gcc.exe")
    set(CMAKE_C_COMPILER "${_PICO_ARM}/arm-none-eabi-gcc.exe")
    set(CMAKE_ASM_COMPILER "${_PICO_ARM}/arm-none-eabi-gcc.exe")
    set(CMAKE_OBJCOPY "${_PICO_ARM}/arm-none-eabi-objcopy.exe")
    set(CMAKE_SIZE "${_PICO_ARM}/arm-none-eabi-size.exe")
else()
    set(CMAKE_C_COMPILER arm-none-eabi-gcc)
    set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
    set(CMAKE_OBJCOPY arm-none-eabi-objcopy)
    set(CMAKE_SIZE arm-none-eabi-size)
endif()
