#pragma once

/* Pin map: Betaflight FOXE/FOXEERF722V4. Both MPU6000 and ICM-42688-P
 * variants populate the same SPI1 bus and PB2 chip-select. */
#define BOARD_NAME "FOXEERF722V4"
#define MOTOR_1_PORT GPIOA
#define MOTOR_1_PIN GPIO_PIN_9
#define MOTOR_2_PORT GPIOA
#define MOTOR_2_PIN GPIO_PIN_8
#define MOTOR_3_PORT GPIOC
#define MOTOR_3_PIN GPIO_PIN_9
#define MOTOR_4_PORT GPIOC
#define MOTOR_4_PIN GPIO_PIN_8
#define STATUS_LED_PORT GPIOC
#define STATUS_LED_PIN GPIO_PIN_15
#define STATUS_LED_ACTIVE_LEVEL GPIO_PIN_RESET
#define BUZZER_PORT GPIOA
#define BUZZER_PIN GPIO_PIN_4
#define BUZZER_ACTIVE_LEVEL GPIO_PIN_RESET
#define BOARD_BUZZER_REQUIRES_TONE 0
#define BOARD_BUZZER_OUTPUT_OPEN_DRAIN 0
#define BOARD_HAS_SBUS_INVERTER_CONTROL 0
#define SBUS_UART_INSTANCE USART1
#define SBUS_UART_IRQn USART1_IRQn
#define SBUS_UART_IRQ_HANDLER USART1_IRQHandler
#define SBUS_UART_CLOCK_ENABLE() __HAL_RCC_USART1_CLK_ENABLE()
#define SBUS_RX_PORT GPIOB
#define SBUS_RX_PIN GPIO_PIN_7
#define SBUS_RX_AF GPIO_AF7_USART1
#define SBUS_UART_NAME "UART1"
#define BOARD_HAS_CRSF 1
#define CRSF_UART_INSTANCE USART1
#define CRSF_UART_IRQn USART1_IRQn
#define CRSF_UART_IRQ_HANDLER USART1_IRQHandler
#define CRSF_UART_CLOCK_ENABLE() __HAL_RCC_USART1_CLK_ENABLE()
#define CRSF_RX_PORT GPIOB
#define CRSF_RX_PIN GPIO_PIN_7
#define CRSF_RX_AF GPIO_AF7_USART1
#define CRSF_UART_NAME "UART1"
#define BOARD_RECEIVER_UART_SHARED 1
#define BOARD_DEFAULT_RECEIVER_PROTOCOL RECEIVER_PROTOCOL_CRSF
#define BOARD_HAS_SELECTABLE_RECEIVER_UART 1
#define BOARD_UART_MASK 0x7EU /* UART1 through UART6. */
#define SETTINGS_ADDRESS 0x08060000U
#define SETTINGS_FLASH_SECTOR FLASH_SECTOR_7
/* External dataflash supplies all flight logs on this target. */
#define FLIGHT_LOG_ADDRESS 0x08040000U
#define FLIGHT_LOG_FLASH_SECTOR FLASH_SECTOR_6
#define BOARD_FLIGHT_LOG_CAPACITY 1U
#define IMU_CS_PORT GPIOB
#define IMU_CS_PIN GPIO_PIN_2
#define IMU_SPI_HANDLE hspi1
#define BOARD_IMU_TYPE IMU_TYPE_AUTODETECT
#define BOARD_CORE_CLOCK_HZ 216000000U
/* Betaflight CW270, normalized to the configurator's -180..180 range. */
#define BOARD_DEFAULT_YAW_DEG -90.0f
#define BOARD_HAS_BATTERY_VOLTAGE 1
#define BATTERY_ADC_PORT GPIOC
#define BATTERY_ADC_PIN GPIO_PIN_0
#define BATTERY_ADC_CHANNEL ADC_CHANNEL_10
#define BATTERY_VOLTAGE_DIVIDER 11.00f
#define BOARD_HAS_VBAT_CALIBRATION 1
#define BOARD_HAS_CURRENT 1
#define CURRENT_ADC_PORT GPIOC
#define CURRENT_ADC_PIN GPIO_PIN_2
#define CURRENT_ADC_CHANNEL ADC_CHANNEL_12
/* Betaflight default when the board does not override current_meter_scale. */
#define CURRENT_METER_SCALE 400.0f
#define BOARD_HAS_OSD 1
#define BOARD_HAS_DIGITAL_OSD 1
#define OSD_SPI_HANDLE hspi3
#define MAX7456_CS_PORT GPIOC
#define MAX7456_CS_PIN GPIO_PIN_3
#define BOARD_DEFAULT_OSD_ENABLED 1U
#define BOARD_DEFAULT_VTX_UART 2U
#define BOARD_HAS_SDCARD 0
#define BOARD_HAS_DATAFLASH 1
#define DATAFLASH_SPI_HANDLE hspi2
#define DATAFLASH_CS_PORT GPIOB
#define DATAFLASH_CS_PIN GPIO_PIN_12
#define BOARD_MOTOR_OUTPUT_LAYOUT 4 /* TIM1 CH2/1 and TIM8 CH4/3. */
